version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo Running build...
      - python -m unittest discover

  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'
